language: rust
rust:
  - stable
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo test --verbose 
