[package]
name = "embedb"
version = "0.1.0"
authors = ["Michael Zehender <michael@beamic.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
